#!/bin/bash
# Initial install script to run on devpod
set -euo pipefail

echo "Running DevPod dotfiles install script..."

# --- Fix TERM for Ghostty ---
#echo "  Setting fallback TERM to xterm-256color"
#export TERM=xterm-256color

# Apply to bash sessions going forward
#echo 'export TERM=xterm-256color' >> ~/.bashrc
#echo 'export TERM=xterm-256color' >> ~/.profile

# --- Install chezmoi & configure dotfile ---
if sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:francisco-cardenas/DevPod-dots.git; then
    echo "Installed chezmoi and ran init apply successfully"
    echo "cleaning up binary of chezmoi. Chezmoi is to be used from mise install."
    rm -rf bin
else
    echo "Failed to install chezmoi or run init --apply" >&2
    exit 1
fi

# -- Check for apt package manager and isntall missing packages ---
if command -v apt >/dev/null; then
    echo "apt detected. Updating package lists..."
    sudo apt update

    if ! command -v vim >/dev/null; then
        echo "Installing vim"
        sudo apt install vim -y
    else
        echo "vim is already installed!"
    fi  
else
  echo "Package manager apt not found. Skipping..."
fi

echo "Devpod Successfully setup!"

exit 0
